import Head from "next/head"
import "./globals.css"
import { Inter } from "next/font/google"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Cool Fun Learning Next.js App!",
  description: "Generated by create next app",
}

export default function RootLayout({ children, home }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* Not sure how to conditionally render the go home link with this Layout style. Will look it up. */}
        {!home ? <Link href="/">{`<=`} Go Back Home</Link> : ""}
      </body>
    </html>
  )
}
